name: image scanner

on:
    workflow_call:
    
jobs:
    image-scan:
        runs-on: ubuntu-latest
        steps:
            - name: dockerhub login
              uses: docker/action-login@v4
              with:
                username: ${{vars.DOCKERHUB_USER}}
                password: ${{secrets.GITHUB_TOKEN}}

            - name: Run Trivy vulnerability scanner in fs mode
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                severity: CRITICAL
                exit-code: 1    